name: solana
version: 0.9.0+1
repository: https://github.com/cryptoplease/cryptoplease-dart
description: >-
  Simple library to interact with the Solana blockchain

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bip39: ^1.0.6
  convert: ^3.0.1
  cryptography: ^2.0.2
  ed25519_hd_key: ^2.1.0
  freezed_annotation: ^0.14.2
  http: ^0.13.3
  json_annotation: ^4.0.1

dev_dependencies:
  borsh: ^0.1.0
  build_runner: ^2.0.6
  freezed: ^0.14.2
  json_serializable: ^5.0.0
  mews_pedantic: ^0.2.1
  test: ^1.17.10
