name: solana
version: 0.29.1
repository: https://github.com/espresso-cash/espresso-cash-public
description: >-
  Dart implementation of Solana JSON RPC API client.
  Provides convenient interface for the RPC methods.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bip39: ^1.0.6
  borsh_annotation: ^0.3.1+3
  collection: ^1.15.0
  convert: ^3.0.1
  cryptography: ^2.5.0
  decimal: ^2.1.0
  ed25519_hd_key: ^2.1.0
  freezed_annotation: ^2.0.0
  http: ^0.13.3
  json_annotation: ^4.4.0
  typed_data: ^1.3.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  borsh: ^0.3.1+2
  build_runner: ^2.1.1
  dart_code_metrics: ^5.7.3
  freezed: ^2.0.0
  json_serializable: ^6.0.0
  jsonrpc_client:
    path: ../jsonrpc_client
  mews_pedantic: ^0.15.0
  test: ^1.17.11
