name: cryptoplease
description: CryptoPlease mobile wallet for Solana
publish_to: "none"
version: 1.34.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.1.0
  cloud_functions: ^3.2.4
  collection: ^1.15.0
  cryptoplease_ui:
    path: ../cryptoplease_ui/
  date_time_format: ^2.0.1
  decimal: ^2.1.0
  dfunc: ^0.7.2
  dio: ^4.0.0
  drift: ^1.5.0
  fast_immutable_collections: ^7.0.3
  firebase_analytics: ^9.1.2
  firebase_core: ^1.4.0
  firebase_dynamic_links: ^4.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.6
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  freezed_annotation: ^1.0.0
  image_picker: ^0.8.3+3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  logging: ^1.0.2
  meta: ^1.7.0
  mews_pedantic: ^0.4.1
  nested: ^1.0.0
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^6.0.0
  qr_code_scanner: ^0.6.1
  qr_flutter: ^4.0.0
  retrofit: ^3.0.1
  rxdart: ^0.27.1
  sentry_flutter: ^6.2.2
  share: ^2.0.4
  shared_preferences: ^2.0.8
  solana:
    path: ../solana/
  sqlite3_flutter_libs: ^0.5.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.12
  uuid: ^3.0.4

dev_dependencies:
  auto_route_generator: ^3.2.0
  bloc_test: ^9.0.2
  build_runner: ^2.0.6
  drift_dev: ^1.5.2
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: ^4.1.5
  flutter_native_splash: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  golden_toolkit: ^0.13.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.4
  mockito: ^5.0.16
  recase: ^4.0.0
  retrofit_generator: ^3.0.0
  storybook_flutter: ^0.10.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/markdowns/

flutter_native_splash:
  color: "#f46640"
