name: solana
version: 0.7.0
repository: https://github.com/antoineherzog/dart-solana-lib
description: >-
  Simple library to interact with the Solana blockchain

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bip39: ^1.0.6
  convert: ^3.0.0
  cryptography: ^2.0.1
  ed25519_hd_key: ^2.0.0
  http: ^0.13.1
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^4.1.0
  mews_pedantic: ^0.2.0
  test: ^1.16.8

