name: wallet_example
description: Demonstrates how to use the solana_seed_vault plugin for wallets

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  collection: ^1.16.0
  dfunc: ^0.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  provider: ^6.0.5
  solana: ^0.29.1
  solana_seed_vault:
    path: ../

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.3
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  mews_pedantic: ^0.15.0-dev.3

flutter:
  uses-material-design: true
