name: jsonrpc_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.3 <4.0.0"

dependencies:
  analyzer: ">=4.4.0 <6.0.0"
  build: ^2.1.1
  http: ^1.1.0
  solana:
    path: ../solana
  source_gen: ^1.1.1

dev_dependencies:
  mews_pedantic: ^0.26.0
  test: ^1.16.0
