name: jsonrpc_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  analyzer: ">=4.4.0 <6.0.0"
  build: ^2.1.1
  http: ^0.13.4
  solana:
    path: ../solana
  source_gen: ^1.1.1

dev_dependencies:
  dart_code_metrics: ^5.7.3
  mews_pedantic: ^0.15.0-dev.3
  test: ^1.16.0
