name: jsonrpc_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  http: ^0.13.4
  source_gen: ^1.1.1
  solana:
    path: ../solana

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
