name: cryptoplease_link
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  collection: ^1.16.0
  crypto: ^3.0.2
  cryptoplease_api:
    path: cryptoplease_api
  dfunc: ^0.8.0+1
  freezed_annotation: ^2.0.1
  json_annotation: ^4.6.0
  mustache_template: ^2.0.0
  shelf: ^1.3.2
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  solana: ^0.26.0

dev_dependencies:
  build_runner: ^2.3.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mews_pedantic: ^0.8.0
  test: ^1.21.6
