name: cryptoplease_link
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  collection: ^1.16.0
  dfunc: ^0.7.2
  freezed_annotation: ^2.0.1
  mustache_template: ^2.0.0
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.2
  mews_pedantic: ^0.6.0
  test: ^1.16.0
