name: solana_seed_vault
description: A reference implementation of the Seed Vault SDK specification for Flutter.
version: 0.0.1
repository: https://github.com/cryptoplease/cryptoplease-dart/tree/master/packages/solana_seed_vault
issue_tracker: https://github.com/cryptoplease/cryptoplease-dart/issues

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"


dependencies:
  dfunc: ^0.8.0+1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  meta: ^1.8.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mews_pedantic: ^0.8.0
  mockito: ^5.3.2
  pigeon: ^3.2.6

flutter:
  plugin:
    platforms:
      android:
        package: com.solana.solana_seed_vault
        pluginClass: SolanaSeedVaultPlugin