name: solana_seed_vault
description: A reference implementation of the Seed Vault SDK specification for Flutter.
version: 0.1.0+1
repository: https://github.com/espresso-cash/espresso-cash-public/tree/master/packages/solana_seed_vault
issue_tracker: https://github.com/espresso-cash/espresso-cash-public/issues

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  meta: ^1.8.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^5.7.3
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mews_pedantic: ^0.15.0-dev.3
  mockito: ^5.3.2
  pigeon: ^7.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.solana.solana_seed_vault
        pluginClass: SolanaSeedVaultPlugin
