name: borsh_annotation
version: 0.3.1+5
repository: https://github.com/espresso-cash/espresso-cash-public
description: >-
  Annotation used to make a Dart object borsh serializable.

environment:
  sdk: ">=2.13.0 <4.0.0"

dev_dependencies:
  mews_pedantic: ^0.26.0
