name: borsh_annotation
version: 0.3.1+3
repository: https://github.com/espresso-cash/espresso-cash-public
description: >-
  Annotation used to make a Dart object borsh serializable.

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^5.7.3
  mews_pedantic: ^0.15.0
