name: borsh_annotation
version: 0.3.1+1
repository: https://github.com/cryptoplease/cryptoplease-dart
description: >-
  Annotation used to make a Dart object borsh serializable.

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  mews_pedantic: ^0.6.0
