name: espressocash_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dio: ^4.0.0
  freezed_annotation: ^2.0.1
  json_annotation: ^4.6.0
  jupiter_aggregator:
    path: ../jupiter_aggregator
  retrofit: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.10
  dart_code_metrics: ^5.7.3
  freezed: ^2.0.2
  json_serializable: ^6.3.1
  mews_pedantic: ^0.15.0
  retrofit_generator: ^4.0.0
