name: espressocash_backend
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  borsh_annotation: ^0.3.1+3
  collection: ^1.17.0
  crypto: ^3.0.2
  dfunc: ^0.8.0+1
  espressocash_api:
    path: espressocash_api
  freezed_annotation: ^2.0.1
  json_annotation: ^4.7.0
  mustache_template: ^2.0.0
  sentry: ^7.4.2
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  solana: ^0.29.1

dev_dependencies:
  borsh: ^0.3.1+2
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.3
  freezed: ^2.1.0+1
  json_serializable: ^6.5.4
  mews_pedantic: ^0.15.0
  test: ^1.24.2
