name: espressocash_backend
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  borsh_annotation: ^0.3.1+5
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.2
  dfunc: ^0.9.0
  dio: ^5.4.0
  espressocash_api:
    path: espressocash_api
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  mustache_template: ^2.0.0
  retrofit: ^4.0.3
  sentry: ^7.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  solana: ^0.30.0+1

dev_dependencies:
  borsh: ^0.3.1+4
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mews_pedantic: ^0.21.0
  retrofit_generator: ^8.0.6
  test: ^1.24.6
