name: cryptoplease_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dio: ^4.0.0
  freezed_annotation: ^2.0.1
  json_annotation: ^4.6.0
  jupiter_aggregator: ^1.0.0
  retrofit: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.3.1
  mews_pedantic: ^0.8.0
  retrofit_generator: ^4.0.0
