name: solana_mobile_client
description: A reference implementation of the Mobile Wallet Adapter (Client) specification for Flutter.
version: 0.1.0+1
repository: https://github.com/espresso-cash/espresso-cash-public/tree/master/packages/solana_mobile_client
issue_tracker: https://github.com/espresso-cash/espresso-cash-public/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^5.7.3
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mews_pedantic: ^0.15.0
  pigeon: ^7.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.solana.solana_mobile_client
        pluginClass: SolanaMobileClientPlugin
