name: solana_mobile_wallet_example
description: Demonstrates how to use the solana_mobile_wallet plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  shared_preferences: ^2.0.15
  solana: ^0.29.1
  solana_mobile_wallet:
    path: ../

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^5.7.3
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  mews_pedantic: ^0.15.0

flutter:
  uses-material-design: true
