name: Run E2E tests
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}-e2e
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "3.10.2"

jobs:
  e2e:
    defaults:
      run:
        working-directory: packages/espressocash_app
    permissions:
      contents: write
      packages: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - uses: actions/setup-java@v2
        with:
          distribution: "microsoft"
          java-version: "11"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
        with:
          project_id: "cryptoplease-dev"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - run: flutter pub get
      - run: make flutter_build

      - name: "Run E2E tests"
        run: make firebase_e2e
